version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: esg_postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=esg_db
    ports:
      - "5433:5432"
    restart: always

  rabbitmq-broker:
    image: rabbitmq:3-management-alpine
    container_name: esg_rabbitmq
    ports:
      - "5672:5672"   # Message pathaune port
      - "15672:15672" # Browser maa herne UI port
    restart: always
  
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: esg_jaeger
    ports:
      - "16686:16686" # Web UI port
      - "4317:4317"   # OTLP gRPC port (Data receive garne)
    restart: always